vk_token: "token"
app_logfile: "/home/user/go/vk-parser-program/internal/logger/app.log"
app_host: "localhost"
app_port: "8080"
db_host: "localhost"
db_port: "5432"
db_user: "your_db_user"
db_password: "your_db_password"
db_name: "your_db_name"